services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    env_file: .env.dev
    ports:
      - 6333:6333
      - 6334:6334
    expose:
      - 6333
      - 6334
      - 6335
    volumes:
      - ./data:/qdrant/storage
