[project]
name = "frontend"
version = "0.1.0"
description = "Frontend"
readme = "README.md"
requires-python = "<3.13,>=3.12"
dependencies = [
    "gradio>=5",
    "fastembed>=0.5",
    "tuspy>=1.1",
]

[project.optional-dependencies]
dev = [
    "ruff",
]
